

services:
  backend:
    build: .
    image: easyorder:1.0.0
    container_name: easyorder
    ports:
      - "3000:3000"
    links:
      - easyorder_database
  easyorder_database:
    image: mysql:5.7
    container_name: easyorder_database
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./local/database/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: easyorder
      MYSQL_USER: easyorder
      MYSQL_PASSWORD: easyorder_senha_super_segura
      MYSQL_ROOT_PASSWORD: root